### ISSUE TITLE
CI/CD to run on PRs to dev branch

### ISSUE THREAD

**Issue by rijobro** [openep/openep-py#19]
Just created [this PR](https://github.com/openep/openep-py/pull/18) to the dev branch, but I guess CI/CD is only set to run for master.

**Comment by rijobro** [comment]
Should just require changing these lines to include dev: https://github.com/openep/openep-py/blob/master/.github/workflows/python-app.yml#L8-L10

**Comment by jayrajan** [comment]
Do the same for Dev? 

so it will be:

push: 
         branches: [ Master ]
         branches: [ Dev ]  
pull_request:
         branches: [ Master ]
         branches: [ Dev ]

**Comment by rijobro** [comment]
That might work, but the syntax I see the most often is like this: https://dev.to/github/running-github-actions-ci-cd-triggers-on-specific-branches-5e6m

```yaml
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev
```

Perhaps because of the brackets, the following would be fine (but I don't know):

```yaml
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
```
